### ISSUE TITLE
Non-integer id index exports from Pinecone currently not supported

### ISSUE THREAD

**Issue by surinnin2** [AI-Northstar-Tech/vector-io#29]
Exports from Pinecone Indexes with ids with string values such as "msg-200" does not seem to be supported.

**Comment by dhruv-anand-aintech** [comment]
Hi @surinnin2 this was due to a bug in the code. It has been fixed now. Could you retry?

**Comment by surinnin2** [comment]
Tried it again with a clean git clone and pip install and got the following errors:

![logs](https://github.com/AI-Northstar-Tech/vector-io/assets/79862260/d8baee69-ed3b-4af9-9b00-92a7302a84ac)

**Comment by leo-paz** [comment]
seeing the same on my end with latest

**Comment by dhruv-anand-aintech** [comment]
Hi @leo-paz @surinnin2, sorry for the inconvenience. It was an error on my part. src/export_vdf/pinecone_export.py:151 had a `return []` statement. I have removed that, and pushed to latest main.

It works with string ids now:
```
(base) ➜  vector-io git:(main) ✗ src/export_vdf.py pinecone
Enter the environment of Pinecone instance: 
Enter the name of index to export (hit return to export all): str-id-index
Iterating namespace ''                                             
The ids are not integers. Please provide a range of ids using --id_list_file if you want to export a subset of vectors.               
updating ids set with 1000 new ids...                              
Collecting IDs using random vector search: 100%|█| 1000/1000 [00:00
Collected 1000 ids out of 1000 vectors in 1 tries.                 
Fetching namespaces: 100%|███████████| 1/1 [00:02<00:00,  2.23s/it]
Final Step: Fetching vectors:   0%|       | 0/1000 [00:00<?, ?it/s]
Fetching indexes: 100%|██████████████| 1/1 [00:04<00:00,  4.11s/it]
{
    "version": "0.0.7",
    "file_structure": [
        "vdf_20240130_134908_5e9ff/str-id-index/i1.parquet/1.parquet",
        "vdf_20240130_134908_5e9ff/VDF_META.json"
    ],
    "author": "dhruvanand",
    "exported_from": "pinecone",
    "indexes": {
        "str-id-index": [
            {
                "namespace": "",
                "total_vector_count": 1000,
                "exported_vector_count": 1000,
                "dimensions": 100,
                "model_name": "text-embedding-ada-002",
                "vector_columns": [
                    "vector"
                ],
                "data_path": "str-id-index/i1.parquet",
                "metric": "Cosine"
            }
        ]
    },
    "exported_at": "2024-01-30T13:49:13.797117+05:30"
}
Export to disk completed. Exported to: vdf_20240130_134908_5e9ff/
Time taken to export data:  00:00:09
```

**Comment by neeraj-codebuddy** [comment]
Hey @dhruv-anand-aintech I'm still getting this error. Any idea what might be causing it?

```
The ids are not integers. Please provide a range of ids using --id_list_file if you want to export a subset of vectors.
updating ids set with 1619 new ids...
Collecting IDs using random vector search: 100%|███████████████████████████████████████████████████████████████████| 1619/1619 [00:00<00:00, 2968.29it/s]
Collected 1619 ids out of 1619 vectors in 1 tries.
Fetching namespaces:   0%|                                                                                                        | 0/39 [00:02<?, ?it/s]
Fetching indexes:   0%|                                                                                                            | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):|                                                                                             | 0/1619 [00:00<?, ?it/s]
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf.py", line 279, in <module>
    main()
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf.py", line 256, in main
    export_obj = export_pinecone(args)
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf.py", line 68, in export_pinecone
    pinecone_export.get_data()
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf/pinecone_export.py", line 334, in get_data
    index_meta = self.get_data_for_index(index_name)
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf/pinecone_export.py", line 448, in get_data_for_index
    total_size += self.save_vectors_to_parquet(
  File "/home/neeraj/codebuddy/vector-io/src/export_vdf/vdb_export_cls.py", line 42, in save_vectors_to_parquet
    df = vectors_df.merge(metadata_df, on="id", how="left")
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 10805, in merge
    return merge(
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 170, in merge
    op = _MergeOperation(
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 794, in __init__
    ) = self._get_merge_keys()
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/reshape/merge.py", line 1297, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/neeraj/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 1910, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'id'
Final Step: Fetching vectors:   0%|                                                                                             | 0/1619 [00:00<?, ?it/s]
```

**Comment by dhruv-anand-aintech** [comment]
Hi @neeraj-codebuddy, I've had a couple of people report this, but I'm unable to reproduce the error. Would you be willing to hop on a quick call so that I can debug it with your help?

**Comment by neeraj-codebuddy** [comment]
Sure @dhruv-anand-aintech let me know a suitable time to connect

**Comment by dhruv-anand-aintech** [comment]
Would you be available between 5 and 7 today: https://calendly.com/dhruv-aintech/30min

**Comment by dhruv-anand-aintech** [comment]
Just merged another fix for this. This time it should work. I have tested it with indexes that have multiple namespaces, and metadata missing in some points in some cases.

**Comment by dhruv-anand-aintech** [comment]
https://github.com/AI-Northstar-Tech/vector-io/pull/37

**Comment by dhruv-anand-aintech** [comment]
Closing this out. Please comment here if it still doesn't work with latest main branch.
